name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
            cd /path/to/your/app
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart fastapi
          EOF

